classdef unetMerge6Group1 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromTensorFlow & nnet.layer.Acceleratable
    %unetMerge6Group1
    % Auto-generated by MATLAB on 13-May-2026 17:34:12


    properties
        % Non Trainable Parameters

    end

    properties (Learnable)
        % Trainable parameters

    end

    properties (Hidden)
        % Code literals

        InputLabels
        OutputLabels
        IsTraining
    end

    methods
        function obj = unetMerge6Group1(Name, Type)
            obj.Name = Name;
            obj.Type = Type;
            obj.IsTraining = false;
            obj.NumInputs = 2;
            obj.NumOutputs = 1;
            obj.InputLabels = {'',''};
            obj.OutputLabels = {'BSSSC'};
        end

        function varargout = predict(obj, convDownarm21Elu, up6Concat2)
            import trainedSynthSegModel.ops.*;
            obj.InputLabels{1} = convDownarm21Elu.dims;
            convDownarm21Elu = iPermuteToReverseTF(convDownarm21Elu, 5);

            obj.InputLabels{2} = up6Concat2.dims;
            up6Concat2 = iPermuteToReverseTF(up6Concat2, 5);
            temp{1} = lowLevelOperatorGraph(convDownarm21Elu, up6Concat2, obj);

            % Extract results from function call.
            temp{1} = addOutputLabel(temp{1}, 5, 1, obj);
            varargout{1} = iPermuteToForwardTF(temp{1}, 5);
        end
    end
end


function [concat] = lowLevelOperatorGraph(convDownarm21Elu, up6Concat2, obj)
import trainedSynthSegModel.ops.*;

concat = tfCat(double(4), [5 5], convDownarm21Elu, up6Concat2);
end