classdef unetPredictionGroup1 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromTensorFlow & nnet.layer.Acceleratable
    %unetPredictionGroup1
    % Auto-generated by MATLAB on 13-May-2026 17:34:13


    properties
        % Non Trainable Parameters

    end

    properties (Learnable)
        % Trainable parameters

    end

    properties (Hidden)
        % Code literals

        InputLabels
        OutputLabels
        IsTraining
    end

    methods
        function obj = unetPredictionGroup1(Name, Type)
            obj.Name = Name;
            obj.Type = Type;
            obj.IsTraining = false;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputLabels = {''};
            obj.OutputLabels = {'pt'};
        end

        function varargout = predict(obj, likelihoodBiasAdd)
            import trainedSynthSegModel.ops.*;
            obj.InputLabels{1} = likelihoodBiasAdd.dims;
            likelihoodBiasAdd = iPermuteToReverseTF(likelihoodBiasAdd, 5);
            temp{1} = lowLevelOperatorGraph(likelihoodBiasAdd, obj);

            % Extract results from function call.
            temp{1} = addOutputLabel(temp{1}, 5, 1, obj);
            varargout{1} = iPermuteToForwardTF(temp{1}, 5);
        end
    end
end


function [truediv] = lowLevelOperatorGraph(likelihoodBiasAdd, obj)
import trainedSynthSegModel.ops.*;

Max = tfMax(likelihoodBiasAdd, double(4), true, [5 0]);
sub = minus(likelihoodBiasAdd, Max);
Exp = exp(sub);
Sum = tfSum(Exp, double(4), true, [5 0]);
truediv = rdivide(Exp, Sum);
end